# -*- coding: utf-8 -*-
"""SP24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCjckdpy8XgxQ8lJe6ZnA8mfxO2pWT15
"""

def interpolate(n,h,dict_):
  import numpy as np
  from scipy import interpolate
  dict_keys = dict_.keys()-{'h'}
  if n < min(dict_keys):
    res_list = dict_[min(dict_.keys())]
  elif n > max(dict_keys):
    res_list = dict_[max(dict_keys)]
  elif n in dict_.keys():
    res_list = dict_[n]
  else:
    min_ = max(filter(lambda x: x < n, dict_keys))
    max_ = min(filter(lambda x: x > n, dict_keys))
    w = abs((np.array(dict_[min_])-np.array(dict_[max_]))/(min_-max_))
    res_list = np.array(dict_[min_])+w*(min_-n)
    if h < 0:
      h=0
    elif h>40:
      h=40
    else:
      res = float(interpolate.interp1d(dict_['h'], list(res_list))(h))
    return res